# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngrpc.proto\x12\x04grpc\"8\n\nJobMessage\x12\r\n\x05model\x18\x01 \x01(\t\x12\r\n\x05\x62\x61tch\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\"\x1e\n\x0bServerReply\x12\x0f\n\x07message\x18\x01 \x01(\t2<\n\tScheduler\x12/\n\x06Notify\x12\x10.grpc.JobMessage\x1a\x11.grpc.ServerReply\"\x00\x42\x06\xa2\x02\x03HLWb\x06proto3'
)




_JOBMESSAGE = _descriptor.Descriptor(
  name='JobMessage',
  full_name='grpc.JobMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='grpc.JobMessage.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch', full_name='grpc.JobMessage.batch', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='grpc.JobMessage.mode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=76,
)


_SERVERREPLY = _descriptor.Descriptor(
  name='ServerReply',
  full_name='grpc.ServerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.ServerReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['JobMessage'] = _JOBMESSAGE
DESCRIPTOR.message_types_by_name['ServerReply'] = _SERVERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobMessage = _reflection.GeneratedProtocolMessageType('JobMessage', (_message.Message,), {
  'DESCRIPTOR' : _JOBMESSAGE,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:grpc.JobMessage)
  })
_sym_db.RegisterMessage(JobMessage)

ServerReply = _reflection.GeneratedProtocolMessageType('ServerReply', (_message.Message,), {
  'DESCRIPTOR' : _SERVERREPLY,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ServerReply)
  })
_sym_db.RegisterMessage(ServerReply)


DESCRIPTOR._options = None

_SCHEDULER = _descriptor.ServiceDescriptor(
  name='Scheduler',
  full_name='grpc.Scheduler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='Notify',
    full_name='grpc.Scheduler.Notify',
    index=0,
    containing_service=None,
    input_type=_JOBMESSAGE,
    output_type=_SERVERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULER)

DESCRIPTOR.services_by_name['Scheduler'] = _SCHEDULER

# @@protoc_insertion_point(module_scope)
